[workspace]
name = "cellpose_env"
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
pip = "*"
packaging = "*"
numpy = ">=1.24,<2.0"
scipy = "1.11.*"
tifffile = ">=2026.3.3,<2027"
cuda-nvrtc = "12.1.*"
cuda-runtime = "12.1.*"

[pypi-dependencies]
cellpose = ">=3.0,<4.0"
torch = { version = "==2.4.1+cu121", index = "https://download.pytorch.org/whl/cu121" }
torchvision = { version = "==0.19.1+cu121", index = "https://download.pytorch.org/whl/cu121" }
segment-anything = "*"
# Remove numpy and scipy from this list to prevent pip from overwriting conda
opencv-python-headless = "*"
pyqtgraph = ">=0.11.0rc0"
natsort = "*"
google-cloud-storage = "*"
tqdm = "*"
tifffile = "*"
fastremap = "*"
roifile = "*"
pyqt5 = "*"
dask = "*"
distributed = "*"
dask-image = "*"
pyyaml = "*"
zarr = "*"
dask_jobqueue = "*"
bokeh = "*"
fill-voids = "*"
qtpy = "*"
cellstitch-cuda = ">=1.5.4, <2"
